### ISSUE TITLE
Dates are transformed to ISO strings

### ISSUE THREAD

**Issue by ipanasenko** [grebaldi/plow-js#11]
There's a [line](https://github.com/grebaldi/plow-js/blob/master/src/migrations/atoms/set/index.js#L47) `const object = JSON.parse(JSON.stringify(subject));` in src/migrations/atoms/set/index.js, it results in `Date` objects being transformed into ISO strings (e.g. '2016-07-11T18:31:28.608Z').

Why is this line needed?

**Comment by YurkaninRyan** [comment]
Correct me if i'm wrong, but it looks like they are attempting to make object a deep copy of subject, otherwise it would just be a reference to subject.

**Comment by ipanasenko** [comment]
Look like it, but deep copying can be done a little more clever than simple stringify-parse, I think
