### ISSUE TITLE
Error in the $merge function

### ISSUE THREAD

**Issue by Pingu501** [grebaldi/plow-js#12]
Hey There,
just had some trouble with your $merge function and found an very bad bug which is also reproducible in your test files.
In the merge test on line 64 is an quite good example. The test success only if the last key of the last object contains only one character. More than one and the function will start to create objects with sub objects containing the next character of the key.

e.g.:
`const subject = {test: {a: {b: {cdef: 'c'}}}};
$merge('test', {a: {b: {cdef: 'foo'}}}, subject))`

will result in
`{a:{b:{c:{d:{e:{f:'foo}}}}}}`

Hope somebody can help here. I didn't created a solution so far.

Kind regards

Alex

**Comment by grebaldi** [comment]
Hi! 

Thank you for reporting the issue :) Can you confirm that it is solved with the latest release?

**Comment by Pingu501** [comment]
Hey, sorry for the long response time.
Seems to work now, thanks :)
